# Generated by Django 4.1.2 on 2022-10-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, max_length=6, related_name='teams', to='pokemons.pokemon'),
        ),
    ]
